// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Artigo = Collections['artigos']['schema']['_output']
export declare const artigos: Artigo[]

export type Projeto = Collections['projetos']['schema']['_output']
export declare const projetos: Projeto[]

export type Certificado = Collections['certificados']['schema']['_output']
export declare const certificados: Certificado[]
