// This file is generated by Velite

export { default as artigos } from './artigos.json' with { type: 'json' }
export { default as projetos } from './projetos.json' with { type: 'json' }
export { default as certificados } from './certificados.json' with { type: 'json' }